 <!-- Start: Topbar -->
      <header id="topbar" class="alt mt10">
        <div class="topbar-left pt35">
			<h4><b class="text-success">Building 231:</b> Floor 1 </h4>
        </div>
      </header><!-- End: Topbar -->

      <!-- Begin: Content -->
		<?php
		// Database query
			$query  = "SELECT * FROM 231_1 ";
		
			$result = mysqli_query($conn, $query);
			//Test if there was a query error
			if(!$result) { ?>
				<script>
					alert("Database query failed.");
				</script>
			<?php  } ?>
				 
		 <div class="panel-body p20 " id="invoice-item">            
        	<div class="row">
            	<div id="maps" class="col-md-12"> 
					<div >
					
<?php	
	//Populate Table  
	while($row = mysqli_fetch_assoc($result)) { ?>
	
<svg id="mySVG" version="1.1" id="Layer_1" xmlns:x="&ns_extend;" xmlns:i="&ns_ai;" xmlns:graph="&ns_graphs;"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"  viewBox="0 0 1393 1362" 
	 style="enable-background:new 0 0 1393 1362" xml:space="preserve">
		
	
<image overflow="visible" width="3123" height="2643" xlink:href="assets/images/231-1.jpg"  transform="matrix(0.446 0 0 0.5153 0 0)"></image>

<a title="1867" href="add.php?building=231_1&dept=<?php echo $row['1867'];?>&room=1867" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="66" y="1094"  width="128" height="156" <?php echo department($row['1867']);?>/></a>
<a title="1678" href="add.php?building=231_1&dept=<?php echo $row['1678'];?>&room=1678" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="194" y="1135"  width="70" height="115"<?php echo department($row['1678']);?>/></a>
<a title="1674" href="add.php?building=231_1&dept=<?php echo $row['1674'];?>&room=1674" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="264" y="1135"  width="54" height="117"<?php echo department($row['1674']);?>/></a>
<a title="1670" href="add.php?building=231_1&dept=<?php echo $row['1670'];?>&room=1670" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="318" y="1135"  width="65" height="84"<?php echo department($row['1670']);?>/></a>
<a title="1668" href="add.php?building=231_1&dept=<?php echo $row['1668'];?>&room=1668" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="424" y="1174"  width="44" height="76"<?php echo department($row['1668']);?>/></a>
<a title="1662" href="add.php?building=231_1&dept=<?php echo $row['1662'];?>&room=1662" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="473" y="1174"  width="132" height="78"<?php echo department($row['1662']);?>/></a>
<a title="1638" href="add.php?building=231_1&dept=<?php echo $row['1638'];?>&room=1638" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="545" y="932"  width="67" height="186"<?php echo department($row['1638']);?>/></a>
<a title="1638A" href="add.php?building=231_1&dept=<?php echo $row['1638A'];?>&room=1638A" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="545" y="887"  width="66" height="45"<?php echo department($row['1638A']);?>/></a>
<a title="1630" href="add.php?building=231_1&dept=<?php echo $row['1630'];?>&room=1630" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="461" y="864"  width="55" height="36"<?php echo department($row['1630']);?>/></a>
<a title="1637" href="add.php?building=231_1&dept=<?php echo $row['1637'];?>&room=1637" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="434" y="905"  width="82" height="27"<?php echo department($row['1637']);?>/></a>
<a title="1637B" href="add.php?building=231_1&dept=<?php echo $row['1637B'];?>&room=1637B" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="412" y="864"  width="49" height="40"<?php echo department($row['1637B']);?>/></a>
<a title="1637A" href="add.php?building=231_1&dept=<?php echo $row['1637A'];?>&room=1637A" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="378" y="905"  width="56" height="28"<?php echo department($row['1637A']);?>/></a>
<a title="????" href="add.php?building=231_1&dept=<?php echo $row['1379'];?>&room=1379" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="378" y="882"  width="31" height="22"<?php echo department($row['1379']);?>/></a>
<a title="1635" href="add.php?building=231_1&dept=<?php echo $row['1635'];?>&room=1635" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="340" y="882"  width="38" height="51"<?php echo department($row['1635']);?>/></a>
<a title="1623" href="add.php?building=231_1&dept=<?php echo $row['1623'];?>&room=1623" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="392" y="786"  width="219" height="70"<?php echo department($row['1623']);?>/></a>
<a title="1829" href="add.php?building=231_1&dept=<?php echo $row['1829'];?>&room=1829" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="66" y="786"  width="128" height="183"<?php echo department($row['1829']);?>/></a>
<a title="1841" href="add.php?building=231_1&dept=<?php echo $row['1841'];?>&room=1841" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="66" y="969"  width="129" height="124"<?php echo department($row['1841']);?>/></a>
<a title="1640" href="add.php?building=231_1&dept=<?php echo $row['1640'];?>&room=1640" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="228" y="946"  width="102" height="153"<?php echo department($row['1640']);?>/></a>
<a title="1600" href="add.php?building=231_1&dept=<?php echo $row['1600'];?>&room=1600" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="336" y="938"  width="180" height="161"<?php echo department($row['1600']);?>/></a>
<a title="1475" href="add.php?building=231_1&dept=<?php echo $row['1475'];?>&room=1475" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="643" y="1174"  width="77" height="70"<?php echo department($row['1475']);?>/></a>
<a title="1462" href="add.php?building=231_1&dept=<?php echo $row['1462'];?>&room=1462" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="725" y="1088"  width="53" height="136"<?php echo department($row['1462']);?>/></a>
<a title="1456" href="add.php?building=231_1&dept=<?php echo $row['1456'];?>&room=1456" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rectx="725" y="1012"  width="51" height="76"<?php echo department($row['1456']);?>/></a>
<a title="1424" href="add.php?building=231_1&dept=<?php echo $row['1424'];?>&room=1424" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="725" y="882"  width="35" height="64"<?php echo department($row['1424']);?>/></a>
<a title="1423" href="add.php?building=231_1&dept=<?php echo $row['1423'];?>&room=1423" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="725" y="802"  width="38" height="54"<?php echo department($row['1423']);?>/></a>
<a title="1425" href="add.php?building=231_1&dept=<?php echo $row['1425'];?>&room=1425" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="648" y="786"  width="72" height="68"<?php echo department($row['1425']);?>/></a>
<a title="1427" href="add.php?building=231_1&dept=<?php echo $row['1427'];?>&room=1427" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="612" y="786"  width="33" height="70"<?php echo department($row['1427']);?>/></a>
<a title="1441" href="add.php?building=231_1&dept=<?php echo $row['1441'];?>&room=1441" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="611" y="882"  width="108" height="140"<?php echo department($row['1441']);?>/></a>
<a title="1451" href="add.php?building=231_1&dept=<?php echo $row['1451'];?>&room=1451" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="671" y="1022"  width="48" height="76"<?php echo department($row['1451']);?>/></a>
<a title="1275" href="add.php?building=231_1&dept=<?php echo $row['1275'];?>&room=1275" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="803" y="1160"  width="85" height="84"<?php echo department($row['1275']);?>/></a>
<a title="1265" href="add.php?building=231_1&dept=<?php echo $row['1265'];?>&room=1265" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="803" y="1068"  width="87" height="92"<?php echo department($row['1265']);?>/></a>
<a title="1253" href="add.php?building=231_1&dept=<?php echo $row['1253'];?>&room=1253" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="803" y="976"  width="86" height="92"<?php echo department($row['1253']);?>/></a>
<a title="1240" href="add.php?building=231_1&dept=<?php echo $row['1240'];?>&room=1240" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="778" y="892"  width="136" height="84"<?php echo department($row['1240']);?>/></a>
<a title="1245" href="add.php?building=231_1&dept=<?php echo $row['1245'];?>&room=1245" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="778" y="824"  width="52" height="40"<?php echo department($row['1245']);?>/></a>
<a title="1210" href="add.php?building=231_1&dept=<?php echo $row['1210'];?>&room=1210" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="889" y="1152"  width="64" height="56"<?php echo department($row['1210']);?>/></a>
<a title="1212" href="add.php?building=231_1&dept=<?php echo $row['1212'];?>&room=1212" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="888" y="1112"  width="44" height="40"<?php echo department($row['1212']);?>/></a>
<a title="1214" href="add.php?building=231_1&dept=<?php echo $row['1214'];?>&room=1214" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="890" y="1073"  width="43" height="35"<?php echo department($row['1214']);?>/></a>
<a title="1216" href="add.php?building=231_1&dept=<?php echo $row['1216'];?>&room=1216" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="894" y="1031"  width="38" height="37"<?php echo department($row['1216']);?>/></a>
<a title="1200C" href="add.php?building=231_1&dept=<?php echo $row['1200C'];?>&room=1200C" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="894" y="984"  width="57" height="47"<?php echo department($row['1200C']);?>/></a>
<a title="1238" href="add.php?building=231_1&dept=<?php echo $row['1238'];?>&room=1238" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="914" y="933"  width="41" height="39"<?php echo department($row['1238']);?>/></a>
<a title="1236" href="add.php?building=231_1&dept=<?php echo $row['1236'];?>&room=1236" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="919" y="892"  width="32" height="40"<?php echo department($row['1236']);?>/></a>
<a title="1237" href="add.php?building=231_1&dept=<?php echo $row['1237'];?>&room=1237" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="914" y="786"  width="41" height="77"<?php echo department($row['1237']);?>/></a>
<a title="1239" href="add.php?building=231_1&dept=<?php echo $row['1239'];?>&room=1239" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="877" y="786"  width="37" height="74"<?php echo department($row['1239']);?>/></a>
<a title="1240" href="add.php?building=231_1&dept=<?php echo $row['1240'];?>&room=1240" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="783" y="892"  width="131" height="83"<?php echo department($row['1240']);?>/></a>
<a title="1202" href="add.php?building=231_1&dept=<?php echo $row['1202'];?>&room=1202" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="953" y="1170"  width="35" height="30"<?php echo department($row['1202']);?>/></a>
<a title="1204" href="add.php?building=231_1&dept=<?php echo $row['1204'];?>&room=1204" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="953" y="1140"  width="35" height="30"<?php echo department($row['1204']);?>/></a>
<a title="1206" href="add.php?building=231_1&dept=<?php echo $row['1206'];?>&room=1206" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="955" y="1108"  width="34" height="30"<?php echo department($row['1206']);?>/></a>
<a title="1208" href="add.php?building=231_1&dept=<?php echo $row['1208'];?>&room=1208" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="955" y="1077"  width="34" height="27"<?php echo department($row['1208']);?>/></a>
<a title="1200" href="add.php?building=231_1&dept=<?php echo $row['1200'];?>&room=1200" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="988" y="1146"  width="51" height="98"<?php echo department($row['1200']);?>/></a>
<a title="1205" href="add.php?building=231_1&dept=<?php echo $row['1205'];?>&room=1205" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1008" y="1112"  width="31" height="32"<?php echo department($row['1205']);?>/></a>
<a title="1207" href="add.php?building=231_1&dept=<?php echo $row['1207'];?>&room=1207" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1008" y="1077"  width="27" height="32"<?php echo department($row['1207']);?>/></a>
<a title="1209" href="add.php?building=231_1&dept=<?php echo $row['1209'];?>&room=1209" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1008" y="1047"  width="27" height="26"<?php echo department($row['1209']);?>/></a>
<a title="1044" href="add.php?building=231_1&dept=<?php echo $row['1044'];?>&room=1044" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1265" y="1170"  width="48" height="106"<?php echo department($row['1044']);?>/></a>
<a title="1042" href="add.php?building=231_1&dept=<?php echo $row['1042'];?>&room=1042" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1206" y="1174"  width="59" height="102"<?php echo department($row['1042']);?>/></a>
<a title="1040" href="add.php?building=231_1&dept=<?php echo $row['1040'];?>&room=1040" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1146" y="1174"  width="60" height="102"<?php echo department($row['1040']);?>/></a>
<a title="1030" href="add.php?building=231_1&dept=<?php echo $row['1030'];?>&room=1030" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1167" y="1005"  width="73" height="151"<?php echo department($row['1030']);?>/></a>
<a title="1032" href="add.php?building=231_1&dept=<?php echo $row['1032'];?>&room=1032" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1167" y="892"  width="38" height="98"<?php echo department($row['1032']);?>/></a>
<a title="1035" href="add.php?building=231_1&dept=<?php echo $row['1035'];?>&room=1035" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1154" y="786"  width="51" height="74"<?php echo department($row['1035']);?>/></a>
<a title="1201" href="add.php?building=231_1&dept=<?php echo $row['1201'];?>&room=1201" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1039" y="975"  width="112" height="186"<?php echo department($row['1201']);?>/></a>
<a title="1224" href="add.php?building=231_1&dept=<?php echo $row['1224'];?>&room=1224" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="974" y="892"  width="177" height="84"<?php echo department($row['1224']);?>/></a>
<a title="1231" href="add.php?building=231_1&dept=<?php echo $row['1231'];?>&room=1231" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="974" y="786"  width="71" height="78"<?php echo department($row['1231']);?>/></a>
<a title="1513" href="add.php?building=231_1&dept=<?php echo $row['1513'];?>&room=1513" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="580" y="615"  width="25" height="40"<?php echo department($row['1513']);?>/></a>
<a title="1511" href="add.php?building=231_1&dept=<?php echo $row['1511'];?>&room=1511" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="605" y="594"  width="67" height="61"<?php echo department($row['1511']);?>/></a>
<a title="1510" href="add.php?building=231_1&dept=<?php echo $row['1510'];?>&room=1510" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="706" y="607"  width="37" height="66"<?php echo department($row['1510']);?>/></a>
<a title="1318" href="add.php?building=231_1&dept=<?php echo $row['1318'];?>&room=1318" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="859" y="615"  width="35" height="60"<?php echo department($row['1318']);?>/></a>
<a title="1314" href="add.php?building=231_1&dept=<?php echo $row['1314'];?>&room=1314" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="899" y="615"  width="33" height="58"<?php echo department($row['1314']);?>/></a>
<a title="1310" href="add.php?building=231_1&dept=<?php echo $row['1310'];?>&room=1310" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="933" y="615"  width="30" height="58"<?php echo department($row['1310']);?>/></a>
<a title="1308" href="add.php?building=231_1&dept=<?php echo $row['1308'];?>&room=1308" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="974" y="615"  width="33" height="62"<?php echo department($row['1308']);?>/></a>
<a title="1116" href="add.php?building=231_1&dept=<?php echo $row['1116'];?>&room=1116" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1014" y="594"  width="196" height="79"<?php echo department($row['1116']);?>/></a>
<a title="1930" href="add.php?building=231_1&dept=<?php echo $row['1930'];?>&room=1930" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="62" y="505"  width="72" height="84"<?php echo department($row['1930']);?>/></a>
<a title="1934" href="add.php?building=231_1&dept=<?php echo $row['1934'];?>&room=1934" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="62" y="421"  width="72" height="84"<?php echo department($row['1934']);?>/></a>
<a title="1944" href="add.php?building=231_1&dept=<?php echo $row['1944'];?>&room=1944" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="66" y="263"  width="133" height="116"<?php echo department($row['1944']);?>/></a>
<a title="1944A" href="add.php?building=231_1&dept=<?php echo $row['1944A'];?>&room=1944A" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="66" y="114"  width="86" height="121"<?php echo department($row['1944A']);?>/></a>
<a title="1956" href="add.php?building=231_1&dept=<?php echo $row['1956'];?>&room=1956" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="158" y="118"  width="132" height="64"<?php echo department($row['1956']);?>/></a>
<a title="1951" href="add.php?building=231_1&dept=<?php echo $row['1951'];?>&room=1951" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="152" y="182"  width="138" height="28"<?php echo department($row['1951']);?>/></a>
<a title="1950" href="add.php?building=231_1&dept=<?php echo $row['1950'];?>&room=1950" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip">
	<g>
	<rect x="158" y="215"  width="106" height="48"<?php echo department($row['1950']);?>/>
	<rect x="204" y="312"  width="130" height="281"<?php echo department($row['1950']);?>/>
	</g>
</a>
<a title="1931" href="add.php?building=231_1&dept=<?php echo $row['1931'];?>&room=1931" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="404" y="487"  width="42" height="43"<?php echo department($row['1931']);?>/></a>
<a title="1923" href="add.php?building=231_1&dept=<?php echo $row['1923'];?>&room=1923" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="404" y="530"  width="44" height="43"<?php echo department($row['1923']);?>/></a>
<a title="1723" href="add.php?building=231_1&dept=<?php echo $row['1723'];?>&room=1723" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="468" y="530"  width="47" height="41"<?php echo department($row['1723']);?>/></a>
<a title="1725" href="add.php?building=231_1&dept=<?php echo $row['1725'];?>&room=1725" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip">
	<g>
	<rect x="468" y="473"  width="139" height="57"<?php echo department($row['1725']);?>/>
	<rect x="516" y="530"  width="91" height="43"<?php echo department($row['1725']);?>/>
	</g>
</a>
<a title="1729" href="add.php?building=231_1&dept=<?php echo $row['1729'];?>&room=1729" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="535" y="364"  width="72" height="88"<?php echo department($row['1729']);?>/></a>
<a title="1731" href="add.php?building=231_1&dept=<?php echo $row['1731'];?>&room=1731" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="473" y="364"  width="62" height="88"<?php echo department($row['1731']);?>/></a>
<a title="1737" href="add.php?building=231_1&dept=<?php echo $row['1737'];?>&room=1737" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="473" y="263"  width="135" height="88"<?php echo department($row['1737']);?>/></a>
<a title="1737A" href="add.php?building=231_1&dept=<?php echo $row['1737A'];?>&room=1737A" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="557" y="192"  width="48" height="71"<?php echo department($row['1737A']);?>/></a>
<a title="1737B" href="add.php?building=231_1&dept=<?php echo $row['1737B'];?>&room=1737B" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="557" y="129"  width="48" height="63"<?php echo department($row['1737B']);?>/></a>
<a title="1739" href="add.php?building=231_1&dept=<?php echo $row['1739'];?>&room=1739" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="468" y="114"  width="86" height="103"<?php echo department($row['1739']);?>/></a>
<a title="1963" href="add.php?building=231_1&dept=<?php echo $row['1963'];?>&room=1963" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="378" y="114"  width="90" height="110"<?php echo department($row['1963']);?>/></a>
<a title="1963A" href="add.php?building=231_1&dept=<?php echo $row['1963A'];?>&room=1963A" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="336" y="114"  width="40" height="59"<?php echo department($row['1963A']);?>/></a>
<a title="1959" href="add.php?building=231_1&dept=<?php echo $row['1959'];?>&room=1959" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="336" y="173"  width="42" height="52"<?php echo department($row['1959']);?>/></a>
<a title="1945" href="add.php?building=231_1&dept=<?php echo $row['1945'];?>&room=1945" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="334" y="283"  width="44" height="81"<?php echo department($row['1945']);?>/></a>
<a title="1937" href="add.php?building=231_1&dept=<?php echo $row['1937'];?>&room=1937" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="334" y="364"  width="44" height="59"<?php echo department($row['1937']);?>/></a>
<a title="1935" href="add.php?building=231_1&dept=<?php echo $row['1935'];?>&room=1935" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="378" y="364"  width="30" height="59"<?php echo department($row['1935']);?>/></a>
<a title="1929" href="add.php?building=231_1&dept=<?php echo $row['1929'];?>&room=1929" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="409" y="364"  width="59" height="60"<?php echo department($row['1929']);?>/></a>
<a title="1945E" href="add.php?building=231_1&dept=<?php echo $row['1945E'];?>&room=1945E" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="434" y="312"  width="34" height="49"<?php echo department($row['1945E']);?>/></a>
<a title="1945D" href="add.php?building=231_1&dept=<?php echo $row['1945D'];?>&room=1945D" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="434" y="283"  width="34" height="31"<?php echo department($row['1945D']);?>/></a>
<a title="1945C" href="add.php?building=231_1&dept=<?php echo $row['1945C'];?>&room=1945C" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="378" y="283"  width="52" height="28"<?php echo department($row['1945C']);?>/></a>
<a title="1945B" href="add.php?building=231_1&dept=<?php echo $row['1945B'];?>&room=1945B" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="376" y="314"  width="54" height="47"<?php echo department($row['1945B']);?>/></a>
<a title="1500" href="add.php?building=231_1&dept=<?php echo $row['1500'];?>&room=1500" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="672" y="123"  width="64" height="438"<?php echo department($row['1500']);?>/></a>
<a title="1501B" href="add.php?building=231_1&dept=<?php echo $row['1501B'];?>&room=1501B" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="636" y="250"  width="35" height="77"<?php echo department($row['1501B']);?>/></a>
<a title="1501D" href="add.php?building=231_1&dept=<?php echo $row['1501D'];?>&room=1501D" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="636" y="123"  width="30" height="76"<?php echo department($row['1501D']);?>/></a>
<a title="1505" href="add.php?building=231_1&dept=<?php echo $row['1505'];?>&room=1505" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="776" y="210"  width="97" height="379"<?php echo department($row['1505']);?>/></a>
<a title="1325" href="add.php?building=231_1&dept=<?php echo $row['1325'];?>&room=1325" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="873" y="551"  width="58" height="38"<?php echo department($row['1325']);?>/></a>
<a title="1324" href="add.php?building=231_1&dept=<?php echo $row['1324'];?>&room=1324" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="932" y="551"  width="56" height="40"<?php echo department($row['1324']);?>/></a>
<a title="1323" href="add.php?building=231_1&dept=<?php echo $row['1323'];?>&room=1323" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="989" y="551"  width="52" height="40"<?php echo department($row['1323']);?>/></a>
<a title="1329" href="add.php?building=231_1&dept=<?php echo $row['1329'];?>&room=1329" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="873" y="517"  width="58" height="34"<?php echo department($row['1329']);?>/></a>
<a title="1328" href="add.php?building=231_1&dept=<?php echo $row['1328'];?>&room=1328" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="931" y="517"  width="57" height="34"<?php echo department($row['1328']);?>/></a>
<a title="1327" href="add.php?building=231_1&dept=<?php echo $row['1327'];?>&room=1327" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="988" y="517"  width="54" height="32"<?php echo department($row['1327']);?>/></a>
<a title="1333" href="add.php?building=231_1&dept=<?php echo $row['1333'];?>&room=1333" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1014" y="452"  width="25" height="62"<?php echo department($row['1333']);?>/></a>
<a title="1339" href="add.php?building=231_1&dept=<?php echo $row['1339'];?>&room=1339" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1014" y="372"  width="29" height="80"<?php echo department($row['1339']);?>/></a>
<a title="1345" href="add.php?building=231_1&dept=<?php echo $row['1345'];?>&room=1345" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="963" y="312"  width="78" height="58"<?php echo department($row['1345']);?>/></a>
<a title="1351" href="add.php?building=231_1&dept=<?php echo $row['1351'];?>&room=1351" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="877" y="215"  width="164" height="96"<?php echo department($row['1351']);?>/></a>
<a title="1330E" href="add.php?building=231_1&dept=<?php echo $row['1330E'];?>&room=1330E" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="873" y="314"  width="86" height="111"<?php echo department($row['1330E']);?>/></a>
<a title="1330W" href="add.php?building=231_1&dept=<?php echo $row['1330W'];?>&room=1330W" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="873" y="429"  width="86" height="85"<?php echo department($row['1330W']);?>/></a>
<a title="1128" href="add.php?building=231_1&dept=<?php echo $row['1128'];?>&room=1128" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1146" y="445"  width="60" height="126"<?php echo department($row['1128']);?>/></a>
<a title="1140" href="add.php?building=231_1&dept=<?php echo $row['1140'];?>&room=1140" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1146" y="361"  width="65" height="83"<?php echo department($row['1140']);?>/></a>
<a title="1146" href="add.php?building=231_1&dept=<?php echo $row['1146'];?>&room=1146" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1146" y="327"  width="56" height="34"<?php echo department($row['1146']);?>/></a>
<a title="1152" href="add.php?building=231_1&dept=<?php echo $row['1152'];?>&room=1152" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1141" y="283"  width="92" height="42"<?php echo department($row['1152']);?>/></a>
<a title="1155" href="add.php?building=231_1&dept=<?php echo $row['1155'];?>&room=1155" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1233" y="288"  width="36" height="56"<?php echo department($row['1155']);?>/></a>
<a title="1157" href="add.php?building=231_1&dept=<?php echo $row['1157'];?>&room=1157" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1273" y="288"  width="34" height="55"<?php echo department($row['1157']);?>/></a>
<a title="1100" href="add.php?building=231_1&dept=<?php echo $row['1100'];?>&room=1100" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="1217" y="344"  width="90" height="99"<?php echo department($row['1100']);?>/></a>
<a title="1300" href="add.php?building=231_1&dept=<?php echo $row['1300'];?>&room=1300" <?php if($_SESSION["b"]==0 && $_SESSION["b"]!= NULL) { echo 'data-target="#myModal"';} ?> role="button" data-toggle="modal" rel="tooltip"><rect x="959" y="372" fill="none" width="52" height="144" <?php echo department($row['1300']);?>/></a>

</svg>


						
<?php 
	 }
	 
 mysqli_free_result($result);
 ?>

			</div> 
		</div>            
	</div>                 
</div> 

 
<script type="text/javascript">
	var buildingNum = '231_1';
</script>

